In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/tabular-playground-series-jun-2022/sample_submission.csv
/kaggle/input/tabular-playground-series-jun-2022/data.csv

In [2]:
df=pd.read_csv("../input/tabular-playground-series-jun-2022/data.csv")

In [3]:
df.head()

,row_id,F_1_0,F_1_1,F_1_2,F_1_3,F_1_4,F_1_5,F_1_6,F_1_7,F_1_8,...,F_4_5,F_4_6,F_4_7,F_4_8,F_4_9,F_4_10,F_4_11,F_4_12,F_4_13,F_4_14
0,0,-0.354591,-0.464038,2.304115,0.734486,1.696395,0.136285,-0.518344,0.502640,-1.852504,...,3.744152,0.794438,0.265185,-0.561809,0.196480,0.373434,6.206995,3.809505,1.236486,1.182055
1,1,1.380940,-0.499626,-0.418548,1.911725,-0.826130,-1.715371,-0.577091,-1.041486,0.596067,...,-2.895826,-0.738275,2.361818,-0.060753,0.727249,-0.271882,5.232157,-4.218259,-2.724883,-0.063775
2,2,0.256023,-1.059874,NaN,0.345678,1.513814,1.243864,-0.509648,-0.800481,-0.115945,...,2.252834,0.472496,2.491386,0.353381,-0.260682,-0.000833,-0.116457,-2.131747,3.661499,-0.131576
3,3,-0.728420,-2.432399,-2.453602,-0.020509,0.333397,0.086049,-1.787601,0.667011,0.761564,...,2.004600,-4.664806,-0.847211,-0.264249,0.664334,-0.557868,8.499483,-4.738799,-3.054611,0.494152
4,4,0.590212,-0.066127,0.468009,-1.096038,0.119399,-1.809710,0.466358,-0.053196,-0.580320,...,0.976937,2.558883,3.377724,0.846891,0.696032,0.554121,-5.979714,-2.869631,3.733057,-0.722943

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 81 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   row_id  1000000 non-null  int64
 1   F_1_0   981603 non-null   float64
 2   F_1_1   981784 non-null   float64
 3   F_1_2   981992 non-null   float64
 4   F_1_3   981750 non-null   float64
 5   F_1_4   981678 non-null   float64
 6   F_1_5   981911 non-null   float64
 7   F_1_6   981867 non-null   float64
 8   F_1_7   981872 non-null   float64
 9   F_1_8   981838 non-null   float64
 10  F_1_9   981751 non-null   float64
 11  F_1_10  982039 non-null   float64
 12  F_1_11  981830 non-null   float64
 13  F_1_12  981797 non-null   float64
 14  F_1_13  981602 non-null   float64
 15  F_1_14  981961 non-null   float64
 16  F_2_0   1000000 non-null  int64
 17  F_2_1   1000000 non-null  int64
 18  F_2_2   1000000 non-null  int64
 19  F_2_3   1000000 non-null  int64
 20  F_2_4   1000000 non-null  int64
 21  F_2_5   1000000 non-null  int64
 22  F_2_6   1000000 non-null  int64
 23  F_2_7   1000000 non-null  int64
 24  F_2_8   1000000 non-null  int64
 25  F_2_9   1000000 non-null  int64
 26  F_2_10  1000000 non-null  int64
 27  F_2_11  1000000 non-null  int64
 28  F_2_12  1000000 non-null  int64
 29  F_2_13  1000000 non-null  int64
 30  F_2_14  1000000 non-null  int64
 31  F_2_15  1000000 non-null  int64
 32  F_2_16  1000000 non-null  int64
 33  F_2_17  1000000 non-null  int64
 34  F_2_18  1000000 non-null  int64
 35  F_2_19  1000000 non-null  int64
 36  F_2_20  1000000 non-null  int64
 37  F_2_21  1000000 non-null  int64
 38  F_2_22  1000000 non-null  int64
 39  F_2_23  1000000 non-null  int64
 40  F_2_24  1000000 non-null  int64
 41  F_3_0   981971 non-null   float64
 42  F_3_1   981655 non-null   float64
 43  F_3_2   981944 non-null   float64
 44  F_3_3   981946 non-null   float64
 45  F_3_4   981627 non-null   float64
 46  F_3_5   981702 non-null   float64
 47  F_3_6   981808 non-null   float64
 48  F_3_7   981987 non-null   float64
 49  F_3_8   981902 non-null   float64
 50  F_3_9   981894 non-null   float64
 51  F_3_10  981800 non-null   float64
 52  F_3_11  981612 non-null   float64
 53  F_3_12  981703 non-null   float64
 54  F_3_13  981940 non-null   float64
 55  F_3_14  981861 non-null   float64
 56  F_3_15  981762 non-null   float64
 57  F_3_16  981878 non-null   float64
 58  F_3_17  981722 non-null   float64
 59  F_3_18  981911 non-null   float64
 60  F_3_19  981800 non-null   float64
 61  F_3_20  981752 non-null   float64
 62  F_3_21  981604 non-null   float64
 63  F_3_22  981823 non-null   float64
 64  F_3_23  981794 non-null   float64
 65  F_3_24  981855 non-null   float64
 66  F_4_0   981872 non-null   float64
 67  F_4_1   981836 non-null   float64
 68  F_4_2   981505 non-null   float64
 69  F_4_3   981971 non-null   float64
 70  F_4_4   982043 non-null   float64
 71  F_4_5   981937 non-null   float64
 72  F_4_6   981675 non-null   float64
 73  F_4_7   981986 non-null   float64
 74  F_4_8   981824 non-null   float64
 75  F_4_9   981735 non-null   float64
 76  F_4_10  981775 non-null   float64
 77  F_4_11  981881 non-null   float64
 78  F_4_12  981694 non-null   float64
 79  F_4_13  982005 non-null   float64
 80  F_4_14  981733 non-null   float64
dtypes: float64(55), int64(26)
memory usage: 618.0 MB